
package biblioproject;

import biblioproject.Users.User;
import biblioproject.gestion.Emprunt;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author KataTheQueen
 */
public class EmpruntInt extends javax.swing.JFrame {
    public boolean newUser=false;
    int  matId;
    /**
     * Creates new form EmpruntInt
     */
    public EmpruntInt() {
        initComponents();
        materialUsers();  
        NewUser.setVisible(false);
    }
    void materialUsers(){
          //table *** material Emprunteur emprunt 
         try (Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/mydb", "postgres", "root")) {
            //Class.forName("org.postgresql.Driver"); 
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM material");
            while (resultSet.next()) {
                materialListNewUser.addItem(resultSet.getString("nom")); 
            }
            resultSet = statement.executeQuery("SELECT * FROM Emprunteur");
            while (resultSet.next()) {
                ListOfUser.addItem(resultSet.getString("id"));
                
            }
         }catch (SQLException e) {
            System.out.println("Connection failure.");
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NewUser = new javax.swing.JPanel();
        TypeLabel = new javax.swing.JLabel();
        RbStudent = new javax.swing.JRadioButton();
        RbTeacher = new javax.swing.JRadioButton();
        NomLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        materialListNewUser = new javax.swing.JComboBox<>();
        nom = new javax.swing.JTextField();
        motif1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        period1 = new javax.swing.JTextField();
        AjoutNew = new javax.swing.JButton();
        ErrorName = new javax.swing.JLabel();
        ErrorMat1 = new javax.swing.JLabel();
        ErrorDate1 = new javax.swing.JLabel();
        ErrorPeriod1 = new javax.swing.JLabel();
        ListOfUser = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cin = new javax.swing.JTextField();
        CINLabel = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JCalendar();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 668));
        setPreferredSize(new java.awt.Dimension(1000, 668));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 668));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 240));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Nouvel abonnée");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 230, 80));

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Abonnée deja inscrit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 230, 80));

        NewUser.setBackground(new java.awt.Color(255, 255, 204));
        NewUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TypeLabel.setText("Type :");
        NewUser.add(TypeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        g1.add(RbStudent);
        RbStudent.setSelected(true);
        RbStudent.setText("Personnel");
        NewUser.add(RbStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 80, 20));

        g1.add(RbTeacher);
        RbTeacher.setText(" Enseignant ");
        RbTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbTeacherActionPerformed(evt);
            }
        });
        NewUser.add(RbTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        NomLabel.setText("Nom : ");
        NewUser.add(NomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, 20));

        jLabel10.setText("le motif :");
        NewUser.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel11.setText("le matériel :");
        NewUser.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        materialListNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialListNewUserActionPerformed(evt);
            }
        });
        NewUser.add(materialListNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, -1));

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        NewUser.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, -1));
        NewUser.add(motif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, -1));

        jLabel12.setText(" la  date  de l’emprunt : ");
        NewUser.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, -1));

        jLabel13.setText("Durée (par jour ) : ");
        NewUser.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 20));
        NewUser.add(period1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 130, -1));

        AjoutNew.setText("Ajouter");
        AjoutNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutNewActionPerformed(evt);
            }
        });
        NewUser.add(AjoutNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 170, 40));

        ErrorName.setForeground(new java.awt.Color(255, 0, 0));
        ErrorName.setText("erreur  cin déja inscrit");
        NewUser.add(ErrorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 160, 20));

        ErrorMat1.setForeground(new java.awt.Color(255, 0, 0));
        ErrorMat1.setText("nombre de ce matriel est 0 en stocke");
        NewUser.add(ErrorMat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 180, 20));

        ErrorDate1.setForeground(new java.awt.Color(255, 0, 0));
        ErrorDate1.setText("Date incorrect");
        NewUser.add(ErrorDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 150, -1));

        ErrorPeriod1.setForeground(new java.awt.Color(255, 0, 0));
        ErrorPeriod1.setText("Durée invalide");
        NewUser.add(ErrorPeriod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 120, -1));

        ListOfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOfUserActionPerformed(evt);
            }
        });
        NewUser.add(ListOfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, -1));

        jLabel1.setText("CIN : ");
        NewUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });
        NewUser.add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, -1));
        NewUser.add(CINLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, 20));
        NewUser.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 480, 210));

        jPanel1.add(NewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 700, 480));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 90, 80));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ErrorDate1.setVisible(false);
        ErrorName.setVisible(false);
        ErrorPeriod1.setVisible(false);
        ErrorMat1.setVisible(false);
        NewUser.setVisible(false);
        NewUser.setVisible(true);  
        nom.setVisible(true);
        ListOfUser.setVisible(false);
        NomLabel.setVisible(true);
        cin.setVisible(true);
        TypeLabel.setVisible(true);
        RbStudent.setVisible(true);
        RbTeacher.setVisible(true);
        newUser=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ErrorDate1.setVisible(false);
        ErrorName.setVisible(false);
        ErrorPeriod1.setVisible(false);
        ErrorMat1.setVisible(false);
        NewUser.setVisible(false);
        NewUser.setVisible(true);
        TypeLabel.setVisible(false);
        RbStudent.setVisible(false);
        RbTeacher.setVisible(false);
        nom.setVisible(false);
        NomLabel.setVisible(false);
        ListOfUser.setVisible(true);
        cin.setVisible(false);
        newUser=false;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RbTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbTeacherActionPerformed

    private void materialListNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialListNewUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialListNewUserActionPerformed

    private void AjoutNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutNewActionPerformed
        User user1;
        String nomEmp;
        String type;
        Emprunt emp1;
        String motif;
        Date date;
        int duree;
        String material;
        String cinEmp;
        Date dateFin;
        String d1;
        long id;
        int etat;
        boolean error=false;
        
        try (Connection connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/mydb", "postgres", "root")) {
            if(newUser){
                if(RbStudent.isSelected())
                    type="student";
                else
                    type="teacher";
                nomEmp=nom.getText();
                cinEmp=cin.getText();
                try{
                    int x=Integer.parseInt(cinEmp);
                    if(cinEmp.length()!=8){
                        ErrorName.setVisible(true);
                        ErrorName.setText("Cin doit etre composée de 8 chiffres");
                        return;
                    }
                }catch(NumberFormatException e){
                        ErrorName.setVisible(true); 
                        ErrorName.setText("Cin doit etre composée de 8 chiffres");      
                          return;
                }
                user1=new User(cinEmp,type,nomEmp);
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery("SELECT * FROM emprunteur where upper(id) like '"+cinEmp+"'");
                while (resultSet.next()) {
                        ErrorName.setText("Emprunteur deja inscrit");
                        ErrorName.setVisible(true);
                        error=true;
                        break;
                }
                if(error==false){
                  String SQL = "INSERT INTO Emprunteur(id,type,nom) VALUES(?,?,?)";
                  PreparedStatement  pstmt = connection.prepareStatement(SQL,Statement.RETURN_GENERATED_KEYS);
                  pstmt.setString(1,user1.getCin());
                  pstmt.setString(2, user1.getType());
                  pstmt.setString(3, user1.getName());
                  int affectedRows = pstmt.executeUpdate(); 
                  if (affectedRows > 0) {
                    try (ResultSet rs = pstmt.getGeneratedKeys()) {
                        if (rs.next()) {
                            id = rs.getLong(1);
                        }
                    } catch (SQLException ex) {
                        ErrorName.setText("error lors d'ajout");
                        ErrorName.setVisible(true);
                        System.out.println(ex.getMessage());
                    }
                  }
                }
                else 
                    return;
          
            }else{
                cinEmp=(String) ListOfUser.getSelectedItem();  
            }
            motif=motif1.getText();
            try{
                duree=Integer.parseInt(period1.getText());
                if(duree<=0){
                    ErrorPeriod1.setVisible(true);
                    return;
                }
            }catch(NumberFormatException e){
                ErrorPeriod1.setVisible(true);
                return;
            }
            date = convertUtilToSql(calendar.getDate());
            material=(String) materialListNewUser.getSelectedItem();        
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM material where nom like '"+material+"'");
            while (resultSet.next()) {
               this.matId=resultSet.getInt("id");
               if(resultSet.getInt("nbstock")<1){
                   ErrorMat1.setVisible(true);   
                   return;
               } 
            }
            emp1=new Emprunt(cinEmp,this.matId,date,duree,motif);
            String SQL = "INSERT INTO Emprunt(id,dateemp,duree,datefin,idmaterial,idemp,etat,motif) VALUES(DEFAULT,?,?,?,?,?,?,?)";
            PreparedStatement  pstmt = connection.prepareStatement(SQL,Statement.RETURN_GENERATED_KEYS);
            pstmt.setDate(1,emp1.getDate());
            pstmt.setInt(2,emp1.getDuree());
            pstmt.setDate(3,emp1.getFin());
            pstmt.setInt(4,emp1.getMaterial());
            pstmt.setString(5, emp1.getEmprunteur());
            if(emp1.isActive())
                etat=1;
            else
                etat=0;
            pstmt.setInt(6,etat);
            pstmt.setString(7, emp1.getMotif());
            int affectedRows = pstmt.executeUpdate(); 
            if (affectedRows > 0) {
              try (ResultSet rs = pstmt.getGeneratedKeys()) {
                  if (rs.next()) {
                      id = rs.getLong(1);
                  }
               JOptionPane.showMessageDialog(null, 
                        "Emprunt enregistrée", 
                        "Message", 
                        JOptionPane.INFORMATION_MESSAGE);
                int rowsAffected = connection.createStatement().executeUpdate("update material set ,nbstock=nbstock-1 where id='"+this.matId+"'");
                PreparedStatement st = connection.prepareStatement("INSERT INTO historic(id,operation,date) VALUES (default, ?, ?)");
                st.setString(1,"Emprunt");
                st.setDate(2,date);
                st.executeUpdate();
                st.close();
                Home home = new Home();
                home.pack();
                home.setVisible(true);
                this.dispose();
              } catch (SQLException ex) {
                  ErrorName.setText("error lors d'ajout");
                  ErrorName.setVisible(true);
                  System.out.println(ex.getMessage());
              }
            }

            
        }catch (Exception ex) {
            Logger.getLogger(EmpruntInt.class.getName()).log(Level.SEVERE, null, ex);   
    }//GEN-LAST:event_AjoutNewActionPerformed
    }
    private static java.sql.Date convertUtilToSql(java.util.Date uDate) {
        java.sql.Date sDate = new java.sql.Date(uDate.getTime());
        return sDate;
    }
        
    
    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void ListOfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOfUserActionPerformed
        


    }//GEN-LAST:event_ListOfUserActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
          Home home = new Home();
          home.pack();
          //this.setLocationRelativeTo(null); 
          home.setVisible(true);
          this.dispose(); 
         
        
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpruntInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpruntInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpruntInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpruntInt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpruntInt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutNew;
    private javax.swing.JLabel CINLabel;
    private javax.swing.JLabel ErrorDate1;
    private javax.swing.JLabel ErrorMat1;
    private javax.swing.JLabel ErrorName;
    private javax.swing.JLabel ErrorPeriod1;
    private javax.swing.JComboBox<String> ListOfUser;
    private javax.swing.JPanel NewUser;
    private javax.swing.JLabel NomLabel;
    private javax.swing.JRadioButton RbStudent;
    private javax.swing.JRadioButton RbTeacher;
    private javax.swing.JLabel TypeLabel;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JTextField cin;
    private javax.swing.ButtonGroup g1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> materialListNewUser;
    private javax.swing.JTextField motif1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField period1;
    // End of variables declaration//GEN-END:variables
}
